front:
  url: http://www.google.com.br
ninja:
  private:
    url: https://ninjainvoices.herokuapp.com/home_private
  url: https://ninjainvoices.herokuapp.com/login
screenshots:
  path: target/evidences

logging:
  file: target/logs/end_to_end.log